name: C++ and Python Ukol 0 Tests

on:
  push:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!tomasracil/main' # specifically excludes the 'tomasracil/main' branch
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'   # excludes master

jobs:
  python_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Python dependencies
      run: python -m pip install --upgrade pip
    - name: Run Python tests
      run: cd Ukol_0/python && python -m unittest discover || exit 1
  cpp_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install C++ dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev
    - name: Build and run C++ tests
      run: cd Ukol_0/cpp && mkdir -p build && cd build && cmake .. && make && ./mytests || exit 1